id = "alabaster-twilight-theme"
name = "Alabaster Twilight"
version = "0.0.1"
schema_version = 1
authors = ["ChuseCubr <chasevillarroel@gmail.com>"]
description = "Alabaster Twilight"
repository = "https://github.com/ChuseCubr/alabaster-twighlight"
